# Generated by Django 2.0.10 on 2020-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='大类', max_length=50, verbose_name='图书大类')),
                ('small_category', models.CharField(default='小类', max_length=50, verbose_name='图书小分类')),
                ('name', models.CharField(default='无', max_length=100, verbose_name='书名')),
                ('author', models.CharField(default='无', max_length=50, verbose_name='作者')),
                ('store', models.CharField(default='无', max_length=100, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='价格')),
                ('default_image', models.ImageField(null=True, upload_to='', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
    ]
